
FROM rockylinux:9

WORKDIR /app

COPY . /app


RUN yum -y update --skip-broken && \
    yum -y install wget vim && \
    yum clean all

# Set an environment variable
ENV APP_ENV=production

# Default command to keep the container running
CMD ["/bin/bash"]
