# Use the official Rocky Linux 9 image as the base
FROM rockylinux:9

# Set a working directory inside the container
WORKDIR /var/www/html

# Update the system and install the Apache HTTP server
RUN yum -y update --skip-broken && \
    yum -y install httpd && \
    yum clean all

# Copy your website files (if any) into the container
COPY ./index.html /var/www/html/index.html

# Expose the default HTTP port
EXPOSE 80

# Command to start the Apache HTTP server
CMD ["httpd", "-D", "FOREGROUND"]
